### ISSUE TITLE
More options to chart

### ISSUE THREAD

**Issue by fanfy** [pingunaut/wicket-chartjs#14]
The chart.js 1.0.1 (current version from repository) have support for tooltips in charts. Please add more options in ChartOptions or at least upgrade the chart.js and chart.min.js to the latest version.

**Comment by pingunaut** [comment]
working on that :)

**Comment by pingunaut** [comment]
wicket-chartjs 6.19.0 with current chart.js version and the additional options is now available in maven central. could you check if your issue is solved?

**Comment by fanfy** [comment]
Just upgraded and it works :) I had to configure a dependency to a newer version of reflections  in pom because the one from webjars depends on an older version of javaassist (conflicting with hibernate). But with reflections 0.9.9  it works. Thank you.

**Comment by pingunaut** [comment]
cool, noprob. Thx for using it :+1:
