### ISSUE TITLE
Show tooltips

### ISSUE THREAD

**Issue by viewsoft** [pingunaut/wicket-chartjs#16]
Is it possible to show tooltips with values on e.g. line chart panel?
Chart.js has property showTooltips fot it.

**Comment by pingunaut** [comment]
this was already implemented in #14 

i just did an upload to maven central:

<dependency>
    <groupId>com.pingunaut</groupId>
    <artifactId>wicket-chartjs</artifactId>
    <version>6.19.1</version>
</dependency>

please tell me if this is working for you.

I just noticed that there's a new version (1.0.2) of chart.js ...there are some further changes. I'll see if i can add these during the next days

**Comment by viewsoft** [comment]
Thanks a lot. Excellent support :)

**Comment by pingunaut** [comment]
:+1: thanks for using the lib :)
