### ISSUE TITLE
suport for real numbers

### ISSUE THREAD

**Issue by fanfy** [pingunaut/wicket-chartjs#19]
PieChartData only permits integer values. There are scenarios when we want to display double values in a pie (but not limited to it). Is this a limitation of chart.js or one from your library?

Thank you

**Comment by pingunaut** [comment]
This is a limitation added by this library. The javascript works fine with any kind of numbers.
I replaced the old Integer data type and things are working fine still. The next days i'll try to keep everything backward compatible and deploy a new version to maven central.
