### ISSUE TITLE
wicket 6 compatibility

### ISSUE THREAD

**Issue by fanfy** [pingunaut/wicket-chartjs#20]
I saw in pom.xml in master that you upgraded the wicket version to 7 but the artefact id is 6.19.2. Please maintain a seperate version with current fixes (for example 6.20.0) and another one for wicket 7. Probably I'm not the only one still working with wicket 6. Thank you for your library.

**Comment by pingunaut** [comment]
you are right. 
i just uploaded a fresh release 6.20.0 into maven central.
this version uses (and will use) wicket 6. 
it contains the updated to address #19 and future fixes will be ported to this wicket-6 branch also.

could you please check, if this matches your requirements? (can take some hours until new version can be found in maven central...)

thanks for using the lib :+1: 
regards

**Comment by pingunaut** [comment]
done

**Comment by chrisco484** [comment]
We're still on Wicket 6.x also - so this support for 6.x is great! :)
