### ISSUE TITLE
LineDataSet: carry label information

### ISSUE THREAD

**Issue by littleyoda** [pingunaut/wicket-chartjs#22]
Hi

It would be nice if you can also add label information to the LineDataSet.
see https://github.com/pingunaut/wicket-chartjs/pull/13

Thanks

**Comment by pingunaut** [comment]
i uploaded an updated version 7.0.1-SNAPSHOT. i don't think snapshots are available from maven central. are you able to use https://oss.sonatype.org/content/repositories/snapshots/ to test it?

Regards,
Martin

**Comment by littleyoda** [comment]
thx. Works.
